*** Settings ***
Documentation    DO NOT MANUALLY MODIFY THIS FILE. IT IS GENERATED BY THE FORM MAPPING TOOL
...              A generated resource file for managing resources for ${formName}. To learn how to update
...              this file, please refer to the README.md in the repository x,y,z


*** Keywords ***

Update {$formName} Form
        [Arguments]    ${r"${model}"}
        [Documentation]    Used to update data on the form ${formName}. NOTE this keyword will have a reference of each component, including
        ...                the components that are readonly. Understanding the state of the field must be managed as part of the test.
        ...                The intended use of this keyword is with the python model class ${formName?replace(" ", "")}Model.
        ...                Example Usage:
        ...                ${r"${form_model}"}=    Create ${formName} Model
        ...                Update ${formName} Form    ${r"${form_model}"}
        <#list componentDataMap as item>
        # TODO Incorporate form location into calculation
        Click Location On Form    ${item.bounds.x + item.bounds.width / 2}    ${item.bounds.y + item.bounds.height / 2}
        Enter Text    ${r"${form_model}"}["${item.componentName}"]
        <#sep>

        </#sep>
        </#list>

<#list componentDataMap as item>
Read ${formName} ${item.componentName} Field
        [Documentation]    Used to read the value of the ${item.componentName} field on the ${formName} form.
        # TODO - Incorporate form location into calculation
        <#if item.type == "TextField">
        Double Click Location On Form    ${item.bounds.x + item.bounds.width / 2}    ${item.bounds.y + item.bounds.height / 2}
        Copy Selected Text To Clipboard
        ${r"${value}"}=    Get Clipboard Value
        Clear Clipboard
        [Return]    ${r"${value}"}
        </#if>
        <#if item.type == "ComboBox">
        Set Region   ${item.bounds.x + 5}    ${item.bounds.y + 5}    ${item.bounds.width - 20}    ${item.bounds.height - 5}
        ${r"${value}"}=    Read Text With OCR
        Reset Region
        [Return]    ${r"${value}"}
        </#if>
        <#if item.type == "CheckBox">
        Set Region   ${item.bounds.x + 5}    ${item.bounds.y + 5}    ${item.bounds.width - 20}    ${item.bounds.height - 5}
        ${r"${value}"}=    Exits  selectedCheckbox.png
        Reset Region
        [Return]    ${r"${value}"}
        </#if>
        <#if item.type == "RadioButton">
        Set Region   ${item.bounds.x + 5}    ${item.bounds.y + 5}    ${item.bounds.width - 20}    ${item.bounds.height - 5}
        ${r"${value}"}=    Exits  selectedRadio.png
        Reset Region
        [Return]    ${r"${value}"}
        </#if>
<#sep>

</#sep>
</#list>